services:
  postgres:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: nest_backend
    build:
      context: ./test-mpel-back
      dockerfile: dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
    networks:
      - app-network

  frontend:
    container_name: next_frontend
    build:
      context: ./test-mpel-front
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
